model:
    n_hidden : [2, 4, 5]
    hidden_size : [32, 64, 128] # NOTE: Perhaps replace with an array describing layers?
    batch_norm : [True, False] # NOTE: Can't be True if batch_size==1. We may add an assertion for this
    activation : 'ReLU'

data: # (does it need to be nested?)
    sites : ["CN-Du2", "US-Me2", "CH-Dav", "ES-Amo", "AU-Wac", "AU-Stp", "GF-Guy"] 
    base_path : "~/epfl/semester_project/databases/T_C_PIPELINE_DATA/"
    nPoints : 50000 # -> decide if we want to truncate, what to do in training?
    exclude_negative : False

pipeline:
    predict_rs: True # If false, we predict gsCO2 instead, and convert it to rs.

train:
    lr: [1e-2, 1e-3, 1e-4]
    weight_decay: [1e-4, 1e-6, 0]
    batch_size: 1000
    k_folds: 3
    k_folds_epochs: 1000 # may be less than the large train epochs to save time
    test_split: 0.2
    random_state: 24 # Assuming the data loading doesn't change, this ensures the test_split will be the same.
    hp_tuning: True # If this is true, hyperparameters are expected to be arrays.

wandb:
  use_wandb: False
  project: "change-project"
  tags: ['default_hyper_parameter_tuning']

name:
    default_hyper_parameter_tuning